-- Poblar la tabla categoria
INSERT INTO AGENDAMLG.CATEGORIA (NOMBRE) 
	VALUES ('Ciclismo')
INSERT INTO AGENDAMLG.CATEGORIA (NOMBRE) 
	VALUES ('Comida')
INSERT INTO AGENDAMLG.CATEGORIA (NOMBRE) 
	VALUES ('Cultura')
INSERT INTO AGENDAMLG.CATEGORIA (NOMBRE) 
	VALUES ('Playa')

-- Poblar la tabla usuario
INSERT INTO AGENDAMLG.USUARIO (TIPO, "ALIAS", NOMBRE, APELLIDOS, EMAIL, PASSWORD, FOTO, FECHANACIMIENTO) 
	VALUES (1, 'usuario', 'Usuario', 'Usuario', 'insertacorreo@correo.com', 'usuario', NULL, CURRENT_DATE)
INSERT INTO AGENDAMLG.USUARIO (TIPO, "ALIAS", NOMBRE, APELLIDOS, EMAIL, PASSWORD, FOTO, FECHANACIMIENTO) 
	VALUES (3, 'periodista', 'Periodista', 'Periodista', 'insertacorreo@correo.com', 'periodista', NULL, CURRENT_DATE)

-- Poblar las preferencias de los usuarios
INSERT INTO AGENDAMLG.PREFERENCIAS (USUARIO_ID, CATEGORIA_ID) 
	VALUES (1, 2)
INSERT INTO AGENDAMLG.PREFERENCIAS (USUARIO_ID, CATEGORIA_ID) 
	VALUES (1, 4)
INSERT INTO AGENDAMLG.PREFERENCIAS (USUARIO_ID, CATEGORIA_ID) 
	VALUES (2, 1)
INSERT INTO AGENDAMLG.PREFERENCIAS (USUARIO_ID, CATEGORIA_ID) 
	VALUES (2, 3)

-- Poblar la tabla eventos
INSERT INTO AGENDAMLG.EVENTO (TIPO, NOMBRE, DESCRIPCION, FECHA, PRECIO, DIRECCION, VALIDADO, CREADOR) 
	VALUES (1, 'Evento sin validar', 'Se trata de un evento de un evento sin validar creado por el usuario', '2017-11-30 16:07:10.343', 2, '2,3, Plaza de la Merced', 0, 1)
INSERT INTO AGENDAMLG.EVENTO (TIPO, NOMBRE, DESCRIPCION, FECHA, PRECIO, DIRECCION, VALIDADO, CREADOR) 
	VALUES (1, 'Evento validado', 'Se trata de un evento validado', '2017-11-29 16:07:33.722', 20, '90,90,Calle Larios', 1, 2)

-- Poblar las tabla categoriaevento
INSERT INTO AGENDAMLG.CATEGORIAEVENTO (EVENTO_ID, CATEGORIA_ID) 
	VALUES (1, 4)
INSERT INTO AGENDAMLG.CATEGORIAEVENTO (EVENTO_ID, CATEGORIA_ID) 
	VALUES (1, 3)
INSERT INTO AGENDAMLG.CATEGORIAEVENTO (EVENTO_ID, CATEGORIA_ID) 
	VALUES (2, 2)
INSERT INTO AGENDAMLG.CATEGORIAEVENTO (EVENTO_ID, CATEGORIA_ID) 
	VALUES (2, 1)

